### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: _gen_distribution_ops.so

### ISSUE THREAD

**Issue by LuisSaybe** [deepmind/trfl#14]
I can not run the example the example file from a basic installation

repository here: https://github.com/LuisSaybe/trfl-gridworld

output:

```sh

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "index.py", line 2, in <module>
    import trfl
  File "/usr/local/lib/python3.6/site-packages/trfl/__init__.py", line 31, in <module>
    from trfl.dist_value_ops import categorical_dist_double_qlearning
  File "/usr/local/lib/python3.6/site-packages/trfl/dist_value_ops.py", line 33, in <module>
    from trfl import distribution_ops
  File "/usr/local/lib/python3.6/site-packages/trfl/distribution_ops.py", line 30, in <module>
    from trfl import gen_distribution_ops
  File "/usr/local/lib/python3.6/site-packages/trfl/gen_distribution_ops.py", line 2, in <module>
    _op_lib = tf.load_op_library(tf.resource_loader.get_path_to_datafile("_gen_distribution_ops.so"))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/site-packages/trfl/_gen_distribution_ops.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewEPFPNS_8OpKernelEPNS_20OpKernelConstructionEE
```

I installed trfl with the following dockerfile

```docker
FROM centos:latest

ENV TERM xterm
ENV SOURCE_DIRECTORY /root/source
ENV PYTHON_VERSION 3.6.8

RUN yum -y update && \
    yum install -y gcc g++ openssl-devel zlib-devel libffi-devel man-pages man nano wget curl git-all unzip && \
    yum clean all && \

    wget --directory-prefix=/opt https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz && \
    tar -xzf /opt/Python-$PYTHON_VERSION.tgz --directory /opt && \
    rm /opt/Python-$PYTHON_VERSION.tgz && \
    cd /opt/Python-$PYTHON_VERSION && \

    ./configure && \
    make && \
    make install && \

    pip3 install --upgrade pip && \
    pip3 install numpy tensorflow tensorflow_probability trfl && \

    mkdir -p $SOURCE_DIRECTORY

WORKDIR $SOURCE_DIRECTORY
```

Then I run 

```sh
docker run -it --rm -v $(pwd)/src:/root/source gridworld-trfl python3 index.py
```

index.py here

```python
import tensorflow as tf
import trfl

# Q-values for the previous and next timesteps, shape [batch_size, num_actions].
q_tm1 = tf.get_variable(
    "q_tm1", initializer=[[1., 1., 0.], [1., 2., 0.]], dtype=tf.float32)
q_t = tf.get_variable(
    "q_t", initializer=[[0., 1., 0.], [1., 2., 0.]], dtype=tf.float32)

# Action indices, discounts and rewards, shape [batch_size].
a_tm1 = tf.constant([0, 1], dtype=tf.int32)
r_t = tf.constant([1, 1], dtype=tf.float32)
pcont_t = tf.constant([0, 1], dtype=tf.float32)  # the discount factor

# Q-learning loss, and auxiliary data.
loss, q_learning = trfl.qlearning(q_tm1, a_tm1, r_t, pcont_t, q_t)

print('loss', loss)
```

**Comment by LuisSaybe** [comment]
Ended up fixing it by locking down tensorflow and tensorflow-probability versions

```dockerfile
FROM centos:latest

ENV TERM xterm
ENV SOURCE_DIRECTORY /root/source
ENV PYTHON_VERSION 3.6.8

RUN yum -y update && \
    yum install -y gcc g++ openssl-devel zlib-devel libffi-devel man-pages man nano wget curl git-all unzip && \
    yum clean all && \

    wget --directory-prefix=/opt https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz && \
    tar -xzf /opt/Python-$PYTHON_VERSION.tgz --directory /opt && \
    rm /opt/Python-$PYTHON_VERSION.tgz && \
    cd /opt/Python-$PYTHON_VERSION && \

    ./configure && \
    make && \
    make install && \

    pip3 install --upgrade pip && \
    pip3 install numpy tensorflow==1.12  tensorflow-probability==0.5.0 trfl && \

    mkdir -p $SOURCE_DIRECTORY

WORKDIR $SOURCE_DIRECTORY
```
