### ISSUE TITLE
policy_gradient_loss batch_shape requirements

### ISSUE THREAD

**Issue by wenkesj** [deepmind/trfl#8]
Why does `policy_gradient_ops.policy_gradient_loss` require batch_shape to be a rank 2 tensor? This would limit the `policy_gradient_loss` operation to only single univariate distributions that implement `log_prob`?

For instance, consider the problem where the actions are multivariate and follow a normal distribution:
```
>>> import tensorflow as tf; tf.enable_eager_execution()
>>> import tensorflow.contrib.eager as tfe
>>> import tensorflow_probability as tfp
>>> loc = tfe.Variable(tf.zeros([5, 5, 2]))
>>> policy = tfp.distributions.Normal(loc=loc, scale=1.)
<tfp.distributions.Normal 'Normal/' batch_shape=(5, 5, 2) event_shape=() dtype=float32>
>>> trfl.policy_gradient_loss(policy, tf.zeros([5, 5, 2]), tf.ones([5, 5]), [loc])
Traceback (most recent call last):
  File "/trfl/policy_gradient_ops.py", line 119, in policy_gradient_loss
    policies_.batch_shape.assert_has_rank(2)
  File "/tensorflow/python/framework/tensor_shape.py", line 728, in assert_has_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (5, 5, 2) must have rank 2
```

I could understand how it is a requirement for a discrete distribution, but does not need to be there?

Thank you for your support and time.

**Comment by mtthss** [comment]
Hi Sam,

The `policy_gradient_ops.policy_gradient_loss` op already supports multivariate distributions. `tf.Distribution` distinguishes between the `_batch_shape` (in our case, time and batch), and `event_shape` (the dimensionality of the samples, e.g., in your case 2).

The assertion only checks the `_batch_shape`, and the `tf.Distribution` that you pass in can have arbitrary `event_shape`. For instance if you want a multivariate gaussian policy you can do:

```
mvn = tfp.distributions.MultivariateNormalDiag(loc=tf.zeros([5,5,2]))
pg_loss = trfl.policy_gradient_loss(mvn, tf.zeros([5, 5, 2]), tf.ones([5, 5]))
```

Here I am using a multivariate gaussian with diagonal covariance matrix, but you can checkout the [tensorflow documentation](https://www.tensorflow.org/api_docs/python/tf/contrib/distributions) for instantiating other multivariate gaussian as `tf.Distribution` objects.

The error in your message arises from the fact that when you feed in `policy = tfp.distributions.Normal(loc=loc, scale=1.)` you are **not** passing a multivariate normal distribution with `batch_shape=[5,5]` and `event_shape=[2]`; **instead** you are passing a univariate (`event_shape=[]`) normal distribution with `batch_shape=[5,5,2]`.

thanks for the comment,

Cheers,
Matteo
